#!/bin/bash
# Script pour préparer les secrets GitHub

echo "╔════════════════════════════════════════════════════════╗"
echo "║     PRÉPARATION DES SECRETS GITHUB POUR LE CD         ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Secrets à ajouter dans GitHub:"
echo ""
echo "1️⃣  SSH_PRIVATE_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Copie de la clé SSH dans le presse-papier..."
cat ~/.ssh/abdellah_takima | pbcopy
echo "✅ Clé SSH copiée dans le presse-papier (Cmd+V pour coller)"
echo ""
echo "Nom du secret:  SSH_PRIVATE_KEY"
echo "Valeur:         [Déjà dans votre presse-papier - Collez avec Cmd+V]"
echo ""

echo "2️⃣  SERVER_HOST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Nom du secret:  SERVER_HOST"
echo "Valeur:         abdellah.sofi1.takima.cloud"
echo "abdellah.sofi1.takima.cloud" | pbcopy
echo "✅ Valeur copiée dans le presse-papier"
echo ""

echo "3️⃣  SERVER_USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Nom du secret:  SERVER_USER"
echo "Valeur:         admin"
echo ""

echo "╔════════════════════════════════════════════════════════╗"
echo "║              INSTRUCTIONS ÉTAPE PAR ÉTAPE              ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "1. Allez sur GitHub:"
echo "   https://github.com/VOTRE_USERNAME/VOTRE_REPO/settings/secrets/actions"
echo ""
echo "2. Cliquez sur 'New repository secret'"
echo ""
echo "3. Ajoutez les 3 secrets un par un:"
echo ""
echo "   Secret 1:"
echo "   - Name: SSH_PRIVATE_KEY"
echo "   - Secret: Collez avec Cmd+V (déjà copié)"
echo "   - Cliquez 'Add secret'"
echo ""
echo "   Secret 2:"
echo "   - Name: SERVER_HOST"
echo "   - Secret: abdellah.sofi1.takima.cloud"
echo "   - Cliquez 'Add secret'"
echo ""
echo "   Secret 3:"
echo "   - Name: SERVER_USER"
echo "   - Secret: admin"
echo "   - Cliquez 'Add secret'"
echo ""
echo "4. Une fois terminé, testez le déploiement:"
echo "   git add ."
echo "   git commit -m 'feat: enable continuous deployment'"
echo "   git push origin main"
echo ""
echo "5. Vérifiez sur GitHub → Actions que le déploiement fonctionne"
echo ""
echo "✅ Prêt à configurer les secrets !"

