---
# Default variables for launch_database role
docker_network_name: app-network
database_container_name: database
database_image: postgres:14-alpine
database_volume: db-data
postgres_db: db
postgres_user: usr
postgres_password: pwd

